# Site settings
email: kheubc@gmail.com
baseurl: "https://ananab.github.io/"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Trophy
description: 
url: ""
twitter_username: 
default_img: 

# Profile settings
name: Kai
profile_img: https://raw.github.ubc.ca/hknaicha/useful_mds_stuff/master/img/squidwad.jpg?token=AAAAKx0kx_OcZ_ijaXZCvMFr1iNqgwrGks5YeAYKwA%3D%3D
profile: 
social:
  github: 

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
